files:
  - source: /src/main/resources/language.yml
    translation: /translations/language-%two_letters_code%.yml
  - source: /src/main/resources/config.yml
    translation: /translations/config-%two_letters_code%.yml
