# To use these prefixes you need additionally the pistonchat.<COLORCODE>
# / indicates disabled!
# This config is configured to be what 2b2t.org has.
whisper:
  from: "&d%player%&d whispers: %message%"
  to: "&dYou whisper to %player%&d: %message%"
hovertext: "&6Message &3%player%"

ignore: "&6Now ignoring &3%player%"
unignore: "&6No longer ignoring &3%player%"
ignorehard: "&6Permanently ignoring %player%&6. This is saved in &4/ignorelist."
unignorehard: "&6No longer permanently ignoring &3%player%"

chatformat: "<%player%&r>"
stripnamecolor: false

consolename: "[console]"

allowpmself: true
allowpmignored: true
onlyhidepms: true

ignorelistsize: 9
prefixes:
  GREEN: ">"
  BLUE: '/'
  RED: '/'
  AQUA: '/'
  GOLD: '/'
  YELLOW: '/'
  GRAY: '/'
  BLACK: '/'
  DARK_GREEN: '/'
  DARK_RED: '/'
  DARK_GRAY: '/'
  DARK_BLUE: '/'
  DARK_AQUA: '/'
  DARK_PURPLE: '/'
  LIGHT_PURPLE: '/'
  ITALIC: '/'
  UNDERLINE: '/'
  BOLD: '/'
  STRIKETHROUGH: '/'