# To use these prefixes you need additionally the pistonchat.<COLORCODE>
# / indicates disabled!
# This config is configured to be what 2b2t.org has.
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
# pistonchat.prefix.green and pistonchat.chatformat.default are given by default.
whisper:
  from: "&d%player%&d whispers: %message%"
  to: "&dYou whisper to %player%&d: %message%"
hovertext: "&6Message &3%player%"

ignore: "&6Now ignoring &3%player%"
unignore: "&6No longer ignoring &3%player%"
ignorehard: "&6Permanently ignoring %player%&6. This is saved in &4/ignorelist."
unignorehard: "&6No longer permanently ignoring &3%player%"

mysql:
  host: "localhost"
  port: 3306
  database: "pistonchat"
  username: "root"
  password: ""

chatformats:
  special: "%player%&r »"
  default: "<%player%&r>"

message-format: "%message%"

resetafterformat: true
stripnamecolor: false

consolename: "[console]"

allowpmself: true
allowpmignored: true
onlyhidepms: true

ignorelistsize: 9
forcewhiteifnoprefix: true
prefixes:
  green:
    prefix: ">"
    color: "GREEN"
