# To use these prefixes you need additionally the pistonchat.<COLORCODE>
# / indicates disabled!
# This config is configured to be what 2b2t.org has.
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
# pistonchat.prefix.green and pistonchat.chatformat.default are given by default.
whisper:
  from: "<light_purple><playername> whispers: <message>"
  to: "<light_purple>You whisper to <playername>: <message>"
hovertext: "<gold>Message <dark_aqua><playername>"

ignore: "<gold>Now ignoring <dark_aqua><playername>"
unignore: "<gold>No longer ignoring <dark_aqua><playername>"
ignorehard: "<gold>Permanently ignoring <playername>. This is saved in <dark_red>/ignorelist</dark_red>."
unignorehard: "<gold>No longer permanently ignoring <dark_aqua><playername>"

mysql:
  host: "localhost"
  port: 3306
  database: "pistonchat"
  username: "root"
  password: ""

use-displayname: true
chatformats:
  special: "<playername> »"
  default: "\<<playername>\>"

message-format: "<format> <message>"

consolename: "[console]"

allowpmself: true
allowpmignored: true
onlyhidepms: true

ignorelistsize: 9
forcewhiteifnoprefix: true
prefixes:
  green:
    prefix: ">"
    color: "GREEN"
