# To use these prefixes you need additionally the pistonchat.<COLORCODE>
# / indicates disabled!
log: "[&2PistonChat&r] "
whisper:
  from: "&d%player% whispers: %message%"
  to: "&dYou whisper to %player%: %message%"
hovertext: "&6Message &3%player%"
prefixes:
  GREEN: ">"
  BLUE: '/'
  RED: '/'
  AQUA: '/'
  GOLD: '/'
  YELLOW: '/'
  GRAY: '/'
  BLACK: '/'
  DARK_GREEN: '/'
  DARK_RED: '/'
  DARK_GRAY: '/'
  DARK_BLUE: '/'
  DARK_AQUA: '/'
  DARK_PURPLE: '/'
  LIGHT_PURPLE: '/'
  ITALIC: '/'
  UNDERLINE: '/'
  BOLD: '/'
  STRIKETHROUGH: '/'