name: PistonChat
version: ${project.version}
main: me.alexprogrammerde.pistonchat.PistonChat
authors: [ AlexProgrammerDE ]
description: An advanced chat plugin for survival/anarchy servers.
website: https://pistonmaster.net/

commands:
  ignore:
    description: Ignore a players chat messages!
    permission: pistonchat.ignore
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> [player]"
    aliases:
      - block
  whisper:
    description: Whisper to a player!
    permission: pistonchat.whisper
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> [player] [message]"
    aliases:
      - tell
      - w
      - pm
      - msg
  reply:
    description: Reply to the last message someone sent to you!
    permission: pistonchat.reply
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> [message]"
    aliases:
      - r
  last:
    description: Message the last person you messaged!
    permission: pistonchat.reply
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> [message]"
    aliases:
      - l
  ignorelist:
    description: List all ignored players!
    permission: pistonchat.ignorelist
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command>"
  togglewhispering:
    description: Prevent getting whispered to!
    permission: pistonchat.togglewhispering
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command>"
    aliases:
      - toggletells
  togglechat:
    description: Prevent getting chat messages!
    permission: pistonchat.togglechat
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command>"
  pistonchat:
    description: Main command!
    permission: pistonchat.command
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> [help|reload]"
permissions:
  pistonchat.last:
    description: Permission for /last!
  pistonchat.reply:
    description: Permission for /reply!
  pistonchat.whisper:
    description: Permission for /whisper!
    children:
      pistonchat.playernamereply: true
      pistonchat.togglewhispering: true
  pistonchat.ignore:
    description: Permission for /ignore!
    children:
      pistonchat.ignorelist: true
  pistonchat.playernamereply:
    description: Make player names clickable!
  pistonchat.greenprefix:
    description: Allows players to use > to make their message green!
  pistonchat.ignorelist:
    description: Permission for /ignorelist!
  pistonchat.togglewhispering:
    description: Permission for /togglewhispering!
  pistonchat.togglechat:
    description: Permission for /togglechat!
  pistonchat.command:
    description: Permission for /pistonchat!
  pistonchat.help:
    description: Permission for /pistonchat help!
    children:
      pistonchat.command: true
  pistonchat.reload:
    description: Permission for /pistonchat reload!
    children:
      pistonchat.command: true
  pistonchat.player:
    description: Default permissions for players!
    children:
      pistonchat.last: true
      pistonchat.reply: true
      pistonchat.whisper: true
      pistonchat.ignore: true
      pistonchat.greenprefix: true
      pistonchat.togglechat: true
      pistonchat.help: true
    default: true
  pistonchat.admin:
    children:
      pistonchat.reload: true
    default: op