name: PistonChat
version: ${project.version}
api-version: 1.13
main: net.pistonmaster.pistonchat.PistonChat
authors: [ AlexProgrammerDE ]
description: An advanced chat plugin for survival/anarchy servers.
website: https://pistonmaster.net/
softdepend: ["PlaceholderAPI"]

commands:
  ignore:
    description: Ignore a players chat messages to the next server restart!
    permission: pistonchat.ignore
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> <player>"
  ignorehard:
    description: Ignore a players chat messages permanently!
    permission: pistonchat.ignorehard
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> <player>"
  whisper:
    description: Whisper to a player!
    permission: pistonchat.whisper
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> <player> <message>"
    aliases:
      - tell
      - w
      - pm
      - msg
  reply:
    description: Reply to the last message someone sent to you!
    permission: pistonchat.reply
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> <message>"
    aliases:
      - r
  last:
    description: Message the last person you messaged!
    permission: pistonchat.reply
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> <message>"
    aliases:
      - l
  ignorelist:
    description: List all ignored players!
    permission: pistonchat.ignorelist
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command>"
  togglewhispering:
    description: Prevent getting whispered to!
    permission: pistonchat.togglewhispering
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command>"
    aliases:
      - toggleprivatemsgs
      - toggletells
  togglechat:
    description: Prevent getting chat messages!
    permission: pistonchat.togglechat
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command>"
  pistonchat:
    description: Main command!
    permission: pistonchat.command
    permission-message: You have no permission to do that!
    usage: "§4Usage: /<command> <help|reload>"
permissions:
  pistonchat.ignorehard:
    description: Permission for /ignorehard!
    children:
      pistonchat.ignorelist: true
  pistonchat.last:
    description: Permission for /last!
  pistonchat.reply:
    description: Permission for /reply!
  pistonchat.whisper:
    description: Permission for /whisper!
    children:
      pistonchat.playernamereply: true
      pistonchat.togglewhispering: true
  pistonchat.ignore:
    description: Permission for /ignore!
    children:
      pistonchat.ignorelist: true
  pistonchat.playernamereply:
    description: Make player names clickable!
  pistonchat.ignorelist:
    description: Permission for /ignorelist!
  pistonchat.togglewhispering:
    description: Permission for /togglewhispering!
  pistonchat.togglechat:
    description: Permission for /togglechat!
  pistonchat.command:
    description: Permission for /pistonchat!
  pistonchat.help:
    description: Permission for /pistonchat help!
    children:
      pistonchat.command: true
  pistonchat.reload:
    description: Permission for /pistonchat reload!
    children:
      pistonchat.command: true
  pistonchat.GREEN:
    description: Just another chat color!
  pistonchat.BLUE:
    description: Just another chat color!
  pistonchat.RED:
    description: Just another chat color!
  pistonchat.AQUA:
    description: Just another chat color!
  pistonchat.GOLD:
    description: Just another chat color!
  pistonchat.YELLOW:
    description: Just another chat color!
  pistonchat.GRAY:
    description: Just another chat color!
  pistonchat.BLACK:
    description: Just another chat color!
  pistonchat.DARK_GREEN:
    description: Just another chat color!
  pistonchat.DARK_RED:
    description: Just another chat color!
  pistonchat.DARK_GRAY:
    description: Just another chat color!
  pistonchat.DARK_BLUE:
    description: Just another chat color!
  pistonchat.DARK_AQUA:
    description: Just another chat color!
  pistonchat.DARK_PURPLE:
    description: Just another chat color!
  pistonchat.LIGHT_PURPLE:
    description: Just another chat color!
  pistonchat.ITALIC:
    description: Just another chat color!
  pistonchat.UNDERLINE:
   description: Just another chat color!
  pistonchat.BOLD:
    description: Just another chat color!
  pistonchat.STRIKETHROUGH:
    description: Just another chat color!
  pistonchat.version:
    description: Permission for /pistonchat version
  pistonchat.bypass:
    description: Allows to talk to vanished people or people with whispering disabled.
  pistonchat.player:
    description: Default permissions for players!
    children:
      pistonchat.last: true
      pistonchat.reply: true
      pistonchat.whisper: true
      pistonchat.ignore: true
      pistonchat.ignorehard: true
      pistonchat.togglechat: true
      pistonchat.help: true
      pistonchat.GREEN: true
    default: true
  pistonchat.admin:
    description: Default permissions for admins!
    children:
      pistonchat.reload: true
      pistonchat.version: true
      pistonchat.bypass: true
    default: op