name: Build and upload jar

on: [ push, pull_request ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload PistonChat
        uses: actions/upload-artifact@v5.0.0
        with:
          name: PistonChat
          path: PistonChat/build/libs/*.jar
      - name: Upload PistonMute
        uses: actions/upload-artifact@v5.0.0
        with:
          name: PistonMute
          path: PistonMute/build/libs/*.jar
      - name: Upload PistonFilter
        uses: actions/upload-artifact@v5.0.0
        with:
          name: PistonFilter
          path: PistonFilter/build/libs/*.jar
