name: Build and upload jar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          # Artifact name
          name: PistonChat
          # A file, directory or wildcard pattern that describes what to upload
          path: target/*.jar
